export const EmitType = {
    NOT_AVAILABLE_USER: "not-available-user",
    GET_AVAILABLE_USER: 'get-available-user',
    CREATE_ROOM: 'create-room',
    START_EXAM: 'start-exam',
    START_QUESTION: 'start-question',
    JOIN_ROOM: 'user-join-room',
    AVALABLE_USER: 'available-user',
    USER_CHOOSE_OPTION: 'user-choose-option',
    USER_DISCONNECT: 'disconnect',
    SERVER_SEND_MESSAGE: 'server-send-message',
    USER_SEND_MESSAGE: 'user-send-message',
    SERVER_UPDATE_USER: 'server-update-user',
    SUBMIT_TEST: 'submit-test',
    QUESTION_TIMEOUT: 'question-timeout',
    INVITE_OTHER_USER: 'invite-other-user',
    empty: '',
};
