export const ListenType = {
    INVITE: 'invite',
    SERVER_SEND_AVAILABLE_USERS: 'server-send-available-user',
    EXAM_RESULT: 'exam-result',
    ROOM_NOT_FOUND: 'room-not-found',
    JOIN_ROOM_SUCCESS: 'join-room-success',
    START_EXAM_SUCCESS: 'start-exam-success',
    SERVER_SEND_MESSAGE: 'server-send-message',
    SERVER_UPDATE_USER: 'server-update-user',
    CORRECT_ANSWER: 'option-is-correct',
    CORRECT_ANSWER_BY_SOE: 'option-is-correct-by-soe',
    WRON_ANSWER: 'option-is-wrong',
    CREATE_ROOM_SUCCESS: 'create-room-success',
    START_QUESTION_SUCCESS: 'start-question-success',
    empty: '',
};
