apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam-service
  template:
    metadata:
      labels:
        app: exam-service
    spec:
      containers:
      - name: exam-service
        image: just4codee/examservice
---
apiVersion: v1
kind: Service
metadata:
  name: exam-service-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: exam-service
  ports:
  - name: exam-service
    port: 80
    targetPort: 80
